export const users = [
  {
    id: 1,
    name: "Juan Perez",
    document: "12345678",
    legal: {
      version: 1,
      submitted_at: "2025-11-13T10:00:00Z",
      answers: [
        { fieldId: "fld-1", type: "multi-select", value: ["recursos_impugnatorios", "solicitud_antecedentes_penales"] },
        { fieldId: "fld-2", type: "multi-select", value: ["refugio_apatridia", "recurso_apelacion"] },
        { fieldId: "fld-3", type: "multi-select", value: ["solicitud_cita_identidad_col", "renovacion_cedula_ecu"] },
        { fieldId: "fld-4", type: "multi-select", value: ["revision_contratos"] },
        { fieldId: "fld-5", type: "multi-select", value: ["orientacion_denuncia"] },
        { fieldId: "fld-6", type: "multi-select", value: ["declaracion_consulado_colombia"] },
        { fieldId: "fld-7", type: "multi-select", value: ["referencia_especializada"] },
        { fieldId: "fld-8", type: "multi-select", value: ["elaboracion_contrato"] },
        { fieldId: "fld-9", type: "multi-select", value: ["informacion_general_derechos"] },
        { fieldId: "fld-10", type: "long-text", value: "Caso complejo con múltiples aspectos legales." },
        { fieldId: "fld-11", type: "multi-checkbox", value: ["dni_pais_origen", "cedula"] },
        { fieldId: "fld-12", type: "select", value: "visa_mercosur" },
        { fieldId: "fld-13", type: "multi-select", value: ["visa_mercosur", "visa_21_meses"] },
        { fieldId: "fld-14", type: "long-text", value: "Descripción detallada del caso." },
        { fieldId: "fld-15", type: "long-text", value: "Antecedentes legales relevantes." },
        { fieldId: "fld-16", type: "long-text", value: "Normativa aplicable al caso." },
        { fieldId: "fld-17", type: "long-text", value: "Acciones realizadas hasta la fecha." },
        { fieldId: "fld-18", type: "long-text", value: "Seguimiento y estado actual del caso." }
      ]
    },
    triage: {
      version: 1,
      submitted_at: "2023-10-01T10:00:00Z",
      answers: [
        // Ingreso del servicio
        { fieldId: "fld-1", type: "date", value: "2023-10-01" }, // Fecha de registro
        {
          fieldId: "fld-2",
          type: "multi-select",
          value: ["psicologia", "legal"],
        }, // Motivo de consulta
        { fieldId: "fld-3", type: "select", value: "primera_vez" }, // Servicio activo
        { fieldId: "fld-4", type: "date", value: null }, // Fecha última atención

        // Identificación
        { fieldId: "fld-5", type: "text", value: "Juan Perez" },
        { fieldId: "fld-6", type: "textarea", value: "Av. Siempre Viva 742" },
        { fieldId: "fld-7", type: "text", value: "Centro" },
        { fieldId: "fld-8", type: "text", value: "Quito" },
        { fieldId: "fld-9", type: "text", value: "+59399111222" },
        { fieldId: "fld-10", type: "text", value: "+59322334455" },
        { fieldId: "fld-11", type: "text", value: "juan.perez@example.com" },

        // Matrix documento: DNI vigente
        {
          fieldId: "fld-12",
          type: "matrix",
          selections: [{ row: "dni_origen", column: "vigente" }],
          observations: "Tiene copia física y digital",
        },
        { fieldId: "fld-13", type: "text", value: 12345678 },
        { fieldId: "fld-14", type: "textarea", value: "" },
        { fieldId: "fld-15", type: "date", value: "1995-04-18" },
        { fieldId: "fld-16", type: "number", value: 28 },
        { fieldId: "fld-17", type: "text", value: "Venezuela" },
        { fieldId: "fld-18", type: "date", value: "2021-06-10" },
        { fieldId: "fld-19", type: "select", value: "irregular" },
        {
          fieldId: "fld-20",
          type: "multi-select",
          value: ["vocacion_permanencia"],
        },
        { fieldId: "fld-21", type: "select", value: "hombre" },
        { fieldId: "fld-22", type: "select", value: "masculino" },
        { fieldId: "fld-23", type: "select", value: "mestizo" },
        { fieldId: "fld-24", type: "select", value: "soltero" },
        { fieldId: "fld-25", type: "text", value: "Juan Perez" },
        { fieldId: "fld-26", type: "select", value: "si" },
        { fieldId: "fld-27", type: "select", value: "padre" },

        // Vulnerabilidades (algunos ejemplos marcados)
        { fieldId: "fld-31", type: "checkbox", value: true },
        { fieldId: "fld-32", type: "checkbox", value: true },
        { fieldId: "fld-36", type: "checkbox", value: false },
        { fieldId: "fld-37", type: "checkbox", value: false },
        // Discapacidad con detalle:
        {
          fieldId: "fld-43",
          type: "checkbox",
          value: true,
          extraValue: "Visual (miopía alta)",
        },
        { fieldId: "fld-44", type: "checkbox", value: false },
        { fieldId: "fld-45", type: "checkbox", value: false },

        // Mecanismos de afrontamiento
        { fieldId: "fld-46", type: "checkbox", value: false },
        { fieldId: "fld-47", type: "select", value: "2" }, // comidas diarias
        {
          fieldId: "fld-48",
          type: "multi-select",
          value: ["arrendada", "compartida"],
        },
        { fieldId: "fld-49", type: "text", value: "4" },
        { fieldId: "fld-50", type: "checkbox", value: true },
        { fieldId: "fld-51", type: "checkbox", value: false },
        { fieldId: "fld-52", type: "text", value: "Sin niños en edad escolar" },

        // Socioeconómico
        { fieldId: "fld-53", type: "multi-select", value: ["bachillerato"] },
        { fieldId: "fld-54", type: "text", value: "Técnico en electricidad" },
        {
          fieldId: "fld-55",
          type: "select",
          value: "si",
          extraValue: "Portugués básico",
        },
        {
          fieldId: "fld-56",
          type: "textarea",
          value: "3 años en mantenimiento eléctrico.",
        },
        {
          fieldId: "fld-57",
          type: "multi-select",
          value: ["trabajo_informal"],
        },
        {
          fieldId: "fld-58",
          type: "textarea",
          value: "Instalaciones eléctricas, atención al cliente.",
        },
        { fieldId: "fld-59", type: "text", value: "350 USD" },

        // Acciones
        {
          fieldId: "fld-60",
          type: "multi-select",
          value: ["psicologia", "legal"],
        },
        { fieldId: "fld-61", type: "textarea", value: "" },
        {
          fieldId: "fld-62",
          type: "textarea",
          value: "Asesoría legal por regularización.",
        },
      ],
    },
    socialWork: {
      version: 1,
      submitted_at: "2023-11-01T10:00:00Z",
      answers: [
        { fieldId: "fld-1", type: "long-text", value: "Situación de vulnerabilidad: desempleo y migración reciente." },
        { fieldId: "fld-2", type: "table", value: [ { name: "Ana Perez", age: "35", relationship: "Esposa", marital_status: "Casada", education_level: "Universitario", occupation: "Ingeniera", disability: "Ninguna" }, { name: "Luis Perez", age: "10", relationship: "Hijo", marital_status: "Soltero", education_level: "Primaria", occupation: "Estudiante", disability: "Ninguna" } ] },
        { fieldId: "fld-3", type: "multi-select", value: ["nuclear", "monoparental"] },
        { fieldId: "fld-4", type: "select", value: "masculino" },
        { fieldId: "fld-5", type: "select", value: "heterosexual" },
        { fieldId: "fld-6", type: "long-text", value: "Familia pequeña, migración por seguridad." },
        { fieldId: "fld-7", type: "multi-checkbox", value: ["nna_padre_madre", "nna_trabajo_infantil"] },
        { fieldId: "fld-8", type: "multi-checkbox", value: ["nna_separado"] },
        { fieldId: "fld-9", type: "multi-checkbox", value: ["mujer_riesgo"] },
        { fieldId: "fld-10", type: "multi-checkbox", value: ["am_solo"] },
        { fieldId: "fld-11", type: "multi-checkbox", value: ["padre_jefe_hogar"] },
        { fieldId: "fld-12", type: "multi-checkbox", value: ["discapacidad_visual"] },
        { fieldId: "fld-13", type: "multi-checkbox", value: ["enfermedad_mental", "desnutricion"] },
        { fieldId: "fld-14", type: "multi-checkbox", value: ["tracing_requerido"] },
        { fieldId: "fld-15", type: "multi-checkbox", value: ["falta_documentacion_legal"] },
        { fieldId: "fld-16", type: "multi-checkbox", value: ["vbg_asilo"] },
        { fieldId: "fld-17", type: "multi-checkbox", value: ["tipos_vbg"] },
        { fieldId: "fld-18", type: "multi-select", value: ["persecucion", "busqueda_trabajo"], observations: "Migración por seguridad y empleo." },
        { fieldId: "fld-19", type: "multi-select", value: ["ingreso_irregular"] },
        { fieldId: "fld-20", type: "text", value: "2 meses" },
        { fieldId: "fld-21", type: "text", value: "Quito" },
        { fieldId: "fld-22", type: "select", value: "si" },
        { fieldId: "fld-23", type: "text", value: "Colombia, Perú" },
        { fieldId: "fld-24", type: "text", value: "Junio 2023" },
        { fieldId: "fld-25", type: "long-text", value: "Llegada con apoyo familiar, vivienda temporal." },
        { fieldId: "fld-26", type: "select", value: "si" },
        { fieldId: "fld-27", type: "select", value: "no" },
        { fieldId: "fld-28", type: "long-text", value: "Hipertensión." },
        { fieldId: "fld-29", type: "long-text", value: "Losartán 50mg." },
        { fieldId: "fld-30", type: "select", value: "no" },
        { fieldId: "fld-31", type: "select", value: "no" },
        { fieldId: "fld-32", type: "select", value: "no" },
        { fieldId: "fld-33", type: "select", value: "no" },
        { fieldId: "fld-34", type: "text", value: "0" },
        { fieldId: "fld-35", type: "multi-select", value: [] },
        { fieldId: "fld-36", type: "select", value: "no" },
        { fieldId: "fld-37", type: "text", value: "Nunca" },
        { fieldId: "fld-38", type: "select", value: "no_aplica" },
        { fieldId: "fld-39", type: "select", value: "no_aplica" },
        { fieldId: "fld-40", type: "select", value: "departamento" },
        { fieldId: "fld-41", type: "multi-select", value: ["cemento", "ladrillo"] },
        { fieldId: "fld-42", type: "text", value: "3" },
        { fieldId: "fld-43", type: "text", value: "2" },
        { fieldId: "fld-44", type: "multi-select", value: ["sala", "bano"], observations: "Baño compartido." },
        { fieldId: "fld-45", type: "multi-select", value: ["sin_seguridades"] },
        { fieldId: "fld-46", type: "multi-select", value: ["potable"] },
        { fieldId: "fld-47", type: "multi-select", value: ["fluido_electrico"] },
        { fieldId: "fld-48", type: "multi-select", value: ["luz", "agua", "internet"] },
        { fieldId: "fld-49", type: "select", value: "inseguro" },
        { fieldId: "fld-50", type: "select", value: "3" },
        { fieldId: "fld-51", type: "select", value: "no" },
        { fieldId: "fld-52", type: "long-text", value: "Barrio inseguro, presencia de robos." },
        { fieldId: "fld-53", type: "select", value: "si" },
        { fieldId: "fld-54", type: "multi-select", value: ["derivacion"] },
        { fieldId: "fld-55", type: "text", value: "2023-11-05" },
        { fieldId: "fld-56", type: "text", value: "2023-11-10" },
        { fieldId: "fld-57", type: "text", value: "Apoyo psicológico." },
        { fieldId: "fld-58", type: "text", value: "Referencia a trabajo social." }
      ],
    },
  },
  {
    id: 2,
    name: "Maria Gomez",
    document: "87654321",
    legal: {
      version: 1,
      submitted_at: "2025-11-13T10:00:00Z",
      answers: [
        { fieldId: "fld-1", type: "multi-select", value: ["solicitud_antecedentes_penales"] },
        { fieldId: "fld-2", type: "multi-select", value: ["refugio_extemporanea"] },
        { fieldId: "fld-3", type: "multi-select", value: ["solicitud_apostilla_col"] },
        { fieldId: "fld-4", type: "multi-select", value: ["denuncia_ministerio_trabajo"] },
        { fieldId: "fld-5", type: "multi-select", value: ["referencias_ong"] },
        { fieldId: "fld-6", type: "multi-select", value: ["actualizacion_datos_indemnizacion"] },
        { fieldId: "fld-7", type: "multi-select", value: ["referencia_especializada"] },
        { fieldId: "fld-8", type: "multi-select", value: ["orientacion_deberes_derechos_arrendaticia"] },
        { fieldId: "fld-9", type: "multi-select", value: ["informacion_general_derechos"] },
        { fieldId: "fld-10", type: "long-text", value: "Caso relacionado con violencia doméstica." },
        { fieldId: "fld-11", type: "multi-checkbox", value: ["pasaporte_pais_origen", "visa_temporal"] },
        { fieldId: "fld-12", type: "select", value: "visa_estudiante" },
        { fieldId: "fld-13", type: "select", value: "visa_amparo_permanente" },
        { fieldId: "fld-14", type: "long-text", value: "Descripción detallada del caso." },
        { fieldId: "fld-15", type: "long-text", value: "Antecedentes legales relevantes." },
        { fieldId: "fld-16", type: "long-text", value: "Normativa aplicable al caso." },
        { fieldId: "fld-17", type: "long-text", value: "Acciones realizadas hasta la fecha." },
        { fieldId: "fld-18", type: "long-text", value: "Seguimiento y estado actual del caso." }
      ]
    },
    triage: {
      version: 1,
      submitted_at: "2023-10-02T15:30:00Z",
      answers: [
        // Ingreso del servicio
        { fieldId: "fld-1", type: "date", value: "2023-10-02" },
        {
          fieldId: "fld-2",
          type: "multi-select",
          value: ["trabajo_social", "medios_vida"],
        },
        { fieldId: "fld-3", type: "select", value: "recurrente" },
        { fieldId: "fld-4", type: "date", value: "2023-09-15" },

        // Identificación
        { fieldId: "fld-5", type: "text", value: "Maria Gomez" },
        {
          fieldId: "fld-6",
          type: "textarea",
          value: "Calle 10 y Av. 2, Edificio Sol, piso 3",
        },
        { fieldId: "fld-7", type: "text", value: "Norte" },
        { fieldId: "fld-8", type: "text", value: "Guayaquil" },
        { fieldId: "fld-9", type: "text", value: "+593988877766" },
        { fieldId: "fld-10", type: "text", value: "" },
        { fieldId: "fld-11", type: "text", value: "maria.gomez@example.com" },

        // Matrix documento: Pasaporte caducado + Visa temporal vigente
        {
          fieldId: "fld-12",
          type: "matrix",
          selections: [
            { row: "pasaporte_origen", column: "caducado" },
            { row: "visa_temporal", column: "vigente" },
          ],
          observationsValue: "En trámite de renovación de pasaporte",
        },
        { fieldId: "fld-13", type: "number", value: 87654321 },
        {
          fieldId: "fld-14",
          type: "textarea",
          value: "Presentó denuncia por pérdida de DNI.",
        },
        { fieldId: "fld-15", type: "date", value: "1992-11-05" },
        { fieldId: "fld-16", type: "number", value: 30 },
        { fieldId: "fld-17", type: "text", value: "Colombia" },
        { fieldId: "fld-18", type: "date", value: "2020-02-20" },
        { fieldId: "fld-19", type: "select", value: "regular" },
        {
          fieldId: "fld-20",
          type: "multi-select",
          value: ["vocacion_permanencia"],
        },
        { fieldId: "fld-21", type: "select", value: "mujer" },
        { fieldId: "fld-22", type: "select", value: "femenino" },
        { fieldId: "fld-23", type: "select", value: "mestizo" },
        { fieldId: "fld-24", type: "select", value: "union_hecho" },
        { fieldId: "fld-25", type: "text", value: "Maria Gomez" },
        { fieldId: "fld-26", type: "select", value: "si" },
        { fieldId: "fld-27", type: "select", value: "madre" },

        // Vulnerabilidades
        { fieldId: "fld-33", type: "checkbox", value: false },
        { fieldId: "fld-34", type: "checkbox", value: true }, // Embarazada
        { fieldId: "fld-35", type: "checkbox", value: false },
        { fieldId: "fld-37", type: "checkbox", value: false },
        { fieldId: "fld-43", type: "checkbox", value: false },
        {
          fieldId: "fld-44",
          type: "checkbox",
          value: true,
          extraValue: "Hipotiroidismo",
        },
        { fieldId: "fld-45", type: "checkbox", value: false },

        // Mecanismos de afrontamiento
        { fieldId: "fld-46", type: "checkbox", value: false },
        { fieldId: "fld-47", type: "select", value: "3" },
        { fieldId: "fld-48", type: "multi-select", value: ["arrendada"] },
        { fieldId: "fld-49", type: "text", value: "3" },
        { fieldId: "fld-50", type: "checkbox", value: false },
        { fieldId: "fld-51", type: "checkbox", value: false },
        { fieldId: "fld-52", type: "text", value: "Sí, asisten regularmente" },

        // Socioeconómico
        { fieldId: "fld-53", type: "multi-select", value: ["superior"] },
        {
          fieldId: "fld-54",
          type: "text",
          value: "Administración de Empresas",
        },
        {
          fieldId: "fld-55",
          type: "select",
          value: "si",
          extraValue: "Inglés intermedio",
        },
        {
          fieldId: "fld-56",
          type: "textarea",
          value: "Experiencia en ventas y logística.",
        },
        { fieldId: "fld-57", type: "multi-select", value: ["trabajo_formal"] },
        {
          fieldId: "fld-58",
          type: "textarea",
          value: "Excel, comunicación, gestión de equipos.",
        },
        { fieldId: "fld-59", type: "text", value: "650 USD" },

        // Acciones
        {
          fieldId: "fld-60",
          type: "multi-select",
          value: ["trabajo_social", "promocion_medios_vida"],
        },
        {
          fieldId: "fld-61",
          type: "textarea",
          value: "ONG X para apoyo prenatal.",
        },
        {
          fieldId: "fld-62",
          type: "textarea",
          value: "Mejorar inserción laboral y estabilidad.",
        },
      ],
    },
    socialWork: {
      version: 1,
      submitted_at: "2023-11-02T15:30:00Z",
      answers: [
        { fieldId: "fld-1", type: "long-text", value: "Situación de vulnerabilidad: madre soltera, migración por violencia." },
        { fieldId: "fld-2", type: "table", value: [ { name: "Maria Gomez", age: "30", relationship: "Madre", marital_status: "Union de hecho", education_level: "Superior", occupation: "Administradora", disability: "Hipotiroidismo" }, { name: "Pedro Gomez", age: "5", relationship: "Hijo", marital_status: "Soltero", education_level: "Inicial", occupation: "Estudiante", disability: "Ninguna" } ] },
        { fieldId: "fld-3", type: "multi-select", value: ["monoparental"] },
        { fieldId: "fld-4", type: "select", value: "femenino" },
        { fieldId: "fld-5", type: "select", value: "bisexual" },
        { fieldId: "fld-6", type: "long-text", value: "Migración por violencia doméstica." },
        { fieldId: "fld-7", type: "multi-checkbox", value: ["nna_trabajo_infantil"] },
        { fieldId: "fld-8", type: "multi-checkbox", value: ["nna_no_acompañado"] },
        { fieldId: "fld-9", type: "multi-checkbox", value: ["mujer_sola_riesgo"] },
        { fieldId: "fld-10", type: "multi-checkbox", value: ["am_con_niños"] },
        { fieldId: "fld-11", type: "multi-checkbox", value: ["cuidador_jefe_hogar"] },
        { fieldId: "fld-12", type: "multi-checkbox", value: ["discapacidad_fisica"] },
        { fieldId: "fld-13", type: "multi-checkbox", value: ["embarazo_riesgo"] },
        { fieldId: "fld-14", type: "multi-checkbox", value: ["reunificacion_familiar_requerida"] },
        { fieldId: "fld-15", type: "multi-checkbox", value: ["incapacidad_cubrir_necesidades"] },
        { fieldId: "fld-16", type: "multi-checkbox", value: ["vbg_huida"] },
        { fieldId: "fld-17", type: "multi-checkbox", value: ["trata_personas"] },
        { fieldId: "fld-18", type: "multi-select", value: ["situaciones_violencia", "falta_acceso_medicina"], observations: "Migración por violencia y falta de servicios." },
        { fieldId: "fld-19", type: "multi-select", value: ["ingreso_regular"] },
        { fieldId: "fld-20", type: "text", value: "1 año" },
        { fieldId: "fld-21", type: "text", value: "Guayaquil" },
        { fieldId: "fld-22", type: "select", value: "no" },
        { fieldId: "fld-23", type: "text", value: "Colombia" },
        { fieldId: "fld-24", type: "text", value: "Febrero 2020" },
        { fieldId: "fld-25", type: "long-text", value: "Llegada con hijo menor, vivienda arrendada." },
        { fieldId: "fld-26", type: "select", value: "si" },
        { fieldId: "fld-27", type: "select", value: "si" },
        { fieldId: "fld-28", type: "long-text", value: "Hipotiroidismo." },
        { fieldId: "fld-29", type: "long-text", value: "Levotiroxina." },
        { fieldId: "fld-30", type: "select", value: "no" },
        { fieldId: "fld-31", type: "select", value: "si" },
        { fieldId: "fld-32", type: "select", value: "si" },
        { fieldId: "fld-33", type: "select", value: "si" },
        { fieldId: "fld-34", type: "text", value: "30" },
        { fieldId: "fld-35", type: "multi-select", value: ["fisica"] },
        { fieldId: "fld-36", type: "select", value: "si" },
        { fieldId: "fld-37", type: "text", value: "En los últimos 3 meses" },
        { fieldId: "fld-38", type: "select", value: "si" },
        { fieldId: "fld-39", type: "select", value: "si" },
        { fieldId: "fld-40", type: "select", value: "casa" },
        { fieldId: "fld-41", type: "multi-select", value: ["madera", "adobe"] },
        { fieldId: "fld-42", type: "text", value: "2" },
        { fieldId: "fld-43", type: "text", value: "1" },
        { fieldId: "fld-44", type: "multi-select", value: ["sala", "comedor"], observations: "Casa pequeña, comedor y sala juntos." },
        { fieldId: "fld-45", type: "multi-select", value: ["deteriorada"] },
        { fieldId: "fld-46", type: "multi-select", value: ["entubada"] },
        { fieldId: "fld-47", type: "multi-select", value: ["solar"] },
        { fieldId: "fld-48", type: "multi-select", value: ["luz", "agua"] },
        { fieldId: "fld-49", type: "select", value: "seguro" },
        { fieldId: "fld-50", type: "select", value: "1_2" },
        { fieldId: "fld-51", type: "select", value: "si" },
        { fieldId: "fld-52", type: "long-text", value: "Barrio seguro, pero vivienda deteriorada." },
        { fieldId: "fld-53", type: "select", value: "no" },
        { fieldId: "fld-54", type: "multi-select", value: ["referencia"] },
        { fieldId: "fld-55", type: "text", value: "2023-11-12" },
        { fieldId: "fld-56", type: "text", value: "2023-11-15" },
        { fieldId: "fld-57", type: "text", value: "Apoyo social." },
        { fieldId: "fld-58", type: "text", value: "Referencia a ONG prenatal." }
      ],
    },
  },
  {
    id: 3,
    name: "Carlos Ruiz",
    document: "11223344",
    triage: {
      date: "2023-10-03",
    },
  },
  {
    id: 4,
    name: "Ana Torres",
    document: "44332211",
    triage: {
      date: "2023-10-04",
    },
  },
  { id: 5, name: "Luis Fernandez", document: "55667788" },
  { id: 6, name: "Sofia Martinez", document: "88776655" },
  { id: 7, name: "Miguel Sanchez", document: "99887766" },
  { id: 8, name: "Laura Diaz", document: "66778899" },
  { id: 9, name: "Pedro Lopez", document: "33445566" },
  { id: 10, name: "Elena Ramirez", document: "66554433" },
  { id: 11, name: "Jorge Castillo", document: "77889900" },
  { id: 12, name: "Carmen Morales", document: "00998877" },
  { id: 13, name: "Diego Herrera", document: "22334455" },
  { id: 14, name: "Isabel Jimenez", document: "55443322" },
  { id: 15, name: "Rafael Vargas", document: "88990011" },
];
